### ISSUE TITLE
Where is logo.png?

### ISSUE THREAD

**Issue by tedliosu** [OSUOSC/flyer#2]
When I forked and cloned this repo to my own laptop, I compiled the .tex file using TeXworks, but it notified me that "File 'logo.png' not found". I checked the repo I forked and cloned from (a.k.a. this one) and realized that "logo.png" is indeed not there.  I'm sure it's not a huge problem that this png file is missing, but I'm more than certain we already have a logo for the club? Could anyone please push the correct logo.png into this repo so we may work with a complete .tex file?

**Comment by smacz42** [comment]
Fixed in commit https://github.com/OSUOSC/flyer/commit/4ddb8f8cf69ee1c8ab83ebfea6d522b4b22fd432
